### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Wshao62** [QueenieCplusplus/DataStorage_Hadoop#1]

**Comment by QueenieCplusplus** [comment]
好的，請問。


Wshao62 <notifications@github.com> 於 2020年6月13日 週六 下午2:16寫道：

**Comment by Wshao62** [comment]
Hi



你有即時通嗎？電報，，維信方便嗎？

Queenie Chen <notifications@github.com> 於 2020年6月13日週六 15:42 寫道：

**Comment by QueenieCplusplus** [comment]
先以信件溝通即可。謝謝

Wshao62 <notifications@github.com> 於 2020年6月13日 週六 下午5:57寫道：

**Comment by Wshao62** [comment]
>
> 我想拜師，，，很多地方不懂，，想問很多邊碼



技巧，，，而且第一次遇到同台灣，，，你寫的很業，，，，，，如果不方便沒關係，，，，我留我電報給你，，，，，，我想跟妳學些c+，，，自己科普，，學不來


Telegram:   @Good1034

**Comment by QueenieCplusplus** [comment]
寫程式一開始練的是心態
能否靜得下心看完一篇一章乃至一本
如果你越發興趣，越來越上癮，就會變的熱愛
而非蜻蜓點水
我的老師就是書
你別拜師，敗書為好

https://github.com/QueenieCplusplus/Cplusplus

c++ 可以看這篇


Wshao62 <notifications@github.com> 於 2020年6月13日 週六 下午8:14寫道：

**Comment by Wshao62** [comment]
老師，，你為何那麼生氣，，我是完全不懂裎式跟編碼，，，，網站你寫的很多是帶過而已，，並沒辦法執行

我是因為機緣，，才發現編碼這麼有趣，，，但是沒基礎，，，對我有點難，，，我不會白漂老師，，，，老師收費多少，，，讓我有預算，，拜託教我，，，而我有些軟件，，想跟老師買，，，，但不知怎麼開口，，真的要這樣寄信回信

**Comment by QueenieCplusplus** [comment]
如果要執行，需要安裝 IDE 做編譯，方能產生出執行檔。
編碼只是編碼，還經過編譯器和函式庫處理。

如果你想學寫程式，建議從 python 學起，然後買本自學的書籍，
照篇章安裝 IDE 編譯器，下載程式庫，方才能在本機做練習。

遠端教學效果不好，自學比較有成就感，建議自己買書從頭開始。

而且學 C++ 可以留到之後學，畢竟你說了，你完全不懂，那就從簡單好學的 Python 開始唄！
老師都是引導，寫程式幾乎都靠自己... 所有你遇到的高手都會這麼跟你說的～

Wshao62 <notifications@github.com> 於 2020年6月13日 週六 下午9:55寫道：

**Comment by QueenieCplusplus** [comment]
我沒有要賣的，放在 github 就是公開，您可自行下載。

Queenie Chen <queeniecplusplus@gmail.com> 於 2020年6月14日 週日 上午10:02寫道：

**Comment by Wshao62** [comment]
在嗎？我遇到問題？可指導一下嗎

>

**Comment by QueenieCplusplus** [comment]
不在，不指導，請自習謝謝

Wshao62 <notifications@github.com> 於 2020年6月14日 週日 下午5:50寫道：
